/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate and obtain a development JWT token with embedded RBAC role.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo Login
         * @description One-click demo login without credentials. Enabled ONLY when CRISISMESH_DEMO_MODE=true.
         */
        post: operations["demo_login_auth_demo_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Profile
         * @description Retrieve identity and authorized role of the authenticated token bearer.
         */
        get: operations["get_current_user_profile_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Report
         * @description Submit raw citizen or agency report. Requires OPERATOR or COMMANDER role.
         */
        post: operations["submit_report_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Sensor Reading
         * @description Ingest physical telemetry (water gauges, rain meters). Requires valid HMAC-SHA256 signature.
         */
        post: operations["submit_sensor_reading_sensors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{unit_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Unit Status
         * @description Update emergency unit operational state (idle, en_route, unavailable). Triggers selective re-plan.
         */
        post: operations["update_unit_status_units__unit_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roads/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Block Road
         * @description Dynamically declare a road segment (u, v) or geographical zone blocked by floods.
         */
        post: operations["block_road_roads_block_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Disaster State
         * @description Retrieve full operational snapshot of current disaster response state.
         */
        get: operations["get_disaster_state_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Plan
         * @description Retrieve current proposed or active resource allocation plan.
         */
        get: operations["get_current_plan_plan_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan Diff
         * @description Retrieve delta between previously approved plan and current revision.
         */
        get: operations["get_plan_diff_plan_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/{plan_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Plan
         * @description Authorize resource plan. Strictly enforces Commander role and Ed25519 cryptographic signature.
         */
        post: operations["approve_plan_plan__plan_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/{plan_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Plan
         * @description Commander rejects proposed plan with mandatory operational rationale, triggering re-plan.
         */
        post: operations["reject_plan_plan__plan_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Trail
         * @description Retrieve full append-only tamper-evident audit chain.
         */
        get: operations["get_audit_trail_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Audit Integrity
         * @description Perform mathematical verification of SHA-256 hash chaining from Genesis to head.
         */
        get: operations["verify_audit_integrity_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/security/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Security Events
         * @description Retrieve all security violations, injection attempts, and perimeter alerts.
         */
        get: operations["get_security_events_security_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Scenario
         * @description Reset the operational crisis environment to clean baseline scenario.
         */
        post: operations["reset_scenario_scenario_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Scenario
         * @description Ingest T0 disaster incidents and trigger multi-agent pipeline.
         */
        post: operations["start_scenario_scenario_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step Scenario
         * @description Advance scenario to T+10 change events (submerged car, ambulance breakdown).
         */
        post: operations["step_scenario_scenario_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Play Scenario
         * @description Play through complete disaster response demonstration automatically.
         */
        post: operations["play_scenario_scenario_play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attacks/{attack_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Attack Demonstration
         * @description Simulate an active adversary attack vector to demonstrate live defense mechanisms.
         */
        post: operations["trigger_attack_demonstration_attacks__attack_type__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/usp-proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usp Proof
         * @description Compute live, non-hardcoded comparative benchmarks demonstrating CrisisMesh's core algorithmic USPs:
         *     1. Low-Churn Re-planning: Proves lambda=60 preserves en-route units vs naive (lambda=0) chaotic churn.
         *     2. Uncertainty-Aware Optimization: Evaluates dual-scenario bounds (Report True vs Report False),
         *        proving robust worst-case cost <= naive worst-case cost.
         *     3. Counterfactual Explanation: Provides exact runner-up options and cost deltas for assigned resources.
         */
        get: operations["get_usp_proof_analysis_usp_proof_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Assignment
         * @description Assignment of an emergency unit to a specific incident.
         */
        Assignment: {
            /**
             * Unit Id
             * @description Assigned unit ID
             */
            unit_id: string;
            /**
             * Incident Id
             * @description Target incident ID
             */
            incident_id: string;
            /**
             * Eta Minutes
             * @description Estimated arrival time in minutes
             */
            eta_minutes: number;
            /**
             * Is Provisional
             * @description Flag for provisional assignments on unverified incidents
             * @default false
             */
            is_provisional: boolean;
            /**
             * Requires Human Confirmation
             * @description Human confirmation requirement
             * @default false
             */
            requires_human_confirmation: boolean;
            /**
             * Target Hospital Id
             * @description Assigned destination hospital
             */
            target_hospital_id?: string | null;
            /**
             * Cost
             * @description Computed assignment cost
             * @default 0
             */
            cost: number;
        };
        /** AttackRequest */
        AttackRequest: {
            /** Payload */
            payload?: Record<string, never> | null;
        };
        /** AttackResponse */
        AttackResponse: {
            /** Attack Type */
            attack_type: string;
            /** Result */
            result: string;
            /** Mitigating Layer */
            mitigating_layer: string;
            /** Detail */
            detail: string;
            /** Security Event */
            security_event?: Record<string, never> | null;
        };
        /**
         * ChangeKind
         * @description Classification of plan allocation modifications.
         * @enum {string}
         */
        ChangeKind: "forced_unit_loss" | "optimization_redirect" | "new_assignment";
        /** CounterfactualExplanation */
        CounterfactualExplanation: {
            /** Incident Id */
            incident_id: string;
            /** Incident Title */
            incident_title: string;
            /** Assigned Unit Id */
            assigned_unit_id: string;
            /** Assigned Unit Type */
            assigned_unit_type: string;
            /** Assigned Eta Minutes */
            assigned_eta_minutes: number;
            /** Assigned Cost */
            assigned_cost: number;
            /** Runner Up Unit Id */
            runner_up_unit_id: string;
            /** Runner Up Eta Minutes */
            runner_up_eta_minutes: number;
            /** Runner Up Cost */
            runner_up_cost: number;
            /** Delta Eta Minutes */
            delta_eta_minutes: number;
            /** Delta Cost */
            delta_cost: number;
            /** Rationale */
            rationale: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Mode */
            mode: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Timestamp */
            timestamp: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            role?: components["schemas"]["Role"] | null;
        };
        /** LowChurnProofComparison */
        LowChurnProofComparison: {
            /** Naive Units Redirected */
            naive_units_redirected: number;
            /** Low Churn Units Redirected */
            low_churn_units_redirected: number;
            /** Naive Total Cost */
            naive_total_cost: number;
            /** Low Churn Total Cost */
            low_churn_total_cost: number;
            /** Naive Delay Cost */
            naive_delay_cost: number;
            /** Low Churn Delay Cost */
            low_churn_delay_cost: number;
            /** Naive Switching Cost */
            naive_switching_cost: number;
            /** Low Churn Switching Cost */
            low_churn_switching_cost: number;
            /** Explanation */
            explanation: string;
        };
        /**
         * Plan
         * @description Complete allocation plan produced by Resource Agent.
         */
        Plan: {
            /** Plan Id */
            plan_id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Assignments */
            assignments?: components["schemas"]["Assignment"][];
            /** Unserved Incidents */
            unserved_incidents?: string[];
            cost_breakdown: components["schemas"]["PlanCost"];
            /** Runner Up Per Incident */
            runner_up_per_incident?: {
                [key: string]: components["schemas"]["RunnerUp"];
            };
            /**
             * Status
             * @default PROPOSED
             */
            status: string;
        };
        /** PlanApproveRequest */
        PlanApproveRequest: {
            /** Plan Hash */
            plan_hash?: string | null;
            /** Signature Hex */
            signature_hex?: string | null;
            /** Nonce */
            nonce?: string | null;
            /** Timestamp */
            timestamp?: number | null;
            /**
             * Auto Sign
             * @default false
             */
            auto_sign: boolean;
        };
        /**
         * PlanChange
         * @description Detailed change for a unit in a PlanDiff.
         */
        PlanChange: {
            /** Unit Id */
            unit_id: string;
            /** From Incident Id */
            from_incident_id?: string | null;
            /** To Incident Id */
            to_incident_id?: string | null;
            /** Reason */
            reason: string;
            /** Cost Delta */
            cost_delta: number;
            /** @default optimization_redirect */
            change_kind: components["schemas"]["ChangeKind"];
            /** Eta Before */
            eta_before?: number | null;
            /** Eta After */
            eta_after?: number | null;
            /**
             * Requires Human Decision
             * @default false
             */
            requires_human_decision: boolean;
        };
        /**
         * PlanCost
         * @description Granular cost breakdown of the CP-SAT allocation objective.
         */
        PlanCost: {
            /** Total Cost */
            total_cost: number;
            /** Delay Harm Cost */
            delay_harm_cost: number;
            /** Wasted Dispatch Cost */
            wasted_dispatch_cost: number;
            /** Switching Penalty Cost */
            switching_penalty_cost: number;
            /** Unserved Penalty Cost */
            unserved_penalty_cost: number;
        };
        /**
         * PlanDiff
         * @description Delta comparison between previous approved plan and newly generated plan.
         */
        PlanDiff: {
            /** Old Plan Id */
            old_plan_id?: string | null;
            /** New Plan Id */
            new_plan_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Changes */
            changes?: components["schemas"]["PlanChange"][];
            /**
             * Total Cost Delta
             * @default 0
             */
            total_cost_delta: number;
            /**
             * Units Redirected
             * @default 0
             */
            units_redirected: number;
            /**
             * Requires Human Decision
             * @default false
             */
            requires_human_decision: boolean;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** PlanRejectRequest */
        PlanRejectRequest: {
            /** Reason */
            reason: string;
            /** Forbidden Pairs */
            forbidden_pairs?: [
                string,
                string
            ][] | null;
        };
        /** ReportIngestRequest */
        ReportIngestRequest: {
            /** Text */
            text: string;
            /** Source Id */
            source_id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Ip Address
             * @default 127.0.0.1
             */
            ip_address: string;
        };
        /** ReportIngestResponse */
        ReportIngestResponse: {
            /** Report Id */
            report_id: string | null;
            /** Status */
            status: string;
            /** Is Quarantined */
            is_quarantined: boolean;
            /** Confidence */
            confidence: number;
            /** Security Events */
            security_events?: Record<string, never>[];
        };
        /** RoadBlockRequest */
        RoadBlockRequest: {
            /** U */
            u?: string | null;
            /** V */
            v?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Radius Km */
            radius_km?: number | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "viewer" | "operator" | "commander";
        /**
         * RunnerUp
         * @description Runner-up unit candidate for counterfactual explanations.
         */
        RunnerUp: {
            /** Incident Id */
            incident_id: string;
            /** Unit Id */
            unit_id?: string | null;
            /**
             * Delta Eta Minutes
             * @default 0
             */
            delta_eta_minutes: number;
            /**
             * Delta Cost
             * @default 0
             */
            delta_cost: number;
            /**
             * Reason Not Chosen
             * @default
             */
            reason_not_chosen: string;
        };
        /** SensorIngestRequest */
        SensorIngestRequest: {
            /** Sensor Id */
            sensor_id: string;
            /**
             * Sensor Type
             * @default water_level
             */
            sensor_type: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Value */
            value: number;
            /**
             * Unit
             * @default meters
             */
            unit: string;
            /**
             * Flood Threshold
             * @default 0.5
             */
            flood_threshold: number;
            /** Signature Hex */
            signature_hex: string;
        };
        /**
         * StateSnapshot
         * @description Pydantic model representation of the LangGraph state snapshot for APIs & UI.
         */
        StateSnapshot: {
            /** Incidents */
            incidents?: Record<string, never>;
            /** Units */
            units?: Record<string, never>[];
            /** Hospitals */
            hospitals?: Record<string, never>[];
            /** Verification Labels */
            verification_labels?: Record<string, never>;
            /** Impact Report */
            impact_report?: Record<string, never> | null;
            current_plan?: components["schemas"]["Plan"] | null;
            previous_approved_plan?: components["schemas"]["Plan"] | null;
            plan_diff?: components["schemas"]["PlanDiff"] | null;
            /** Commander Briefing */
            commander_briefing?: Record<string, never> | null;
            /** Pending Approvals */
            pending_approvals?: Record<string, never>[];
            /** Message Log */
            message_log?: Record<string, never>[];
            /** Negotiation History */
            negotiation_history?: Record<string, never>[];
            /** Active Agents */
            active_agents?: string[];
            /**
             * Veto Count
             * @default 0
             */
            veto_count: number;
            /**
             * Step Budget
             * @default 20
             */
            step_budget: number;
            /**
             * Status
             * @default INITIALIZED
             */
            status: string;
            /** Dispatch Error */
            dispatch_error?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Role */
            role: string;
            /** User Id */
            user_id: string;
            /** Public Key Hex */
            public_key_hex?: string | null;
            /**
             * Expires In Seconds
             * @default 86400
             */
            expires_in_seconds: number;
        };
        /** USPProofResponse */
        USPProofResponse: {
            /** Timestamp */
            timestamp: number;
            /** Scenario Stage */
            scenario_stage: string;
            low_churn: components["schemas"]["LowChurnProofComparison"];
            uncertainty_aware: components["schemas"]["UncertaintyProofComparison"];
            counterfactual: components["schemas"]["CounterfactualExplanation"];
        };
        /** UncertaintyProofComparison */
        UncertaintyProofComparison: {
            /** Incident Id */
            incident_id: string;
            /** Incident Title */
            incident_title: string;
            /** Credibility Score */
            credibility_score: number;
            /** Verification Label */
            verification_label: string;
            /** Cost If True Naive */
            cost_if_true_naive: number;
            /** Cost If True Robust */
            cost_if_true_robust: number;
            /** Cost If False Naive */
            cost_if_false_naive: number;
            /** Cost If False Robust */
            cost_if_false_robust: number;
            /** Worst Case Naive */
            worst_case_naive: number;
            /** Worst Case Robust */
            worst_case_robust: number;
            /** Is Robust Le Naive */
            is_robust_le_naive: boolean;
            /** Explanation */
            explanation: string;
        };
        /** UnitStatusUpdateRequest */
        UnitStatusUpdateRequest: {
            /**
             * Status
             * @description Operational state: idle, en_route, unavailable
             */
            status: string;
            /** Current Target Id */
            current_target_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_login_auth_demo_login_post: {
        parameters: {
            query?: {
                /** @description Role to assume: viewer, operator, commander */
                role?: components["schemas"]["Role"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_profile_auth_me_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_report_reports_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_sensor_reading_sensors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_unit_status_units__unit_id__status_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_road_roads_block_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadBlockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_disaster_state_state_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_plan_plan_current_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_diff_plan_diff_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_plan__plan_id__approve_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_plan_plan__plan_id__reject_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_trail_audit_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_integrity_audit_verify_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_security_events_security_events_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_scenario_scenario_reset_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scenario_scenario_start_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_scenario_scenario_step_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    play_scenario_scenario_play_post: {
        parameters: {
            query?: {
                /** @description Playback speed multiplier */
                speed?: number;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_attack_demonstration_attacks__attack_type__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attack_type: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AttackRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usp_proof_analysis_usp_proof_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["USPProofResponse"];
                };
            };
        };
    };
}
